-- AlterTable
ALTER TABLE `Creator` ADD COLUMN `image1` VARCHAR(191) NULL,
    ADD COLUMN `image10` VARCHAR(191) NULL,
    ADD COLUMN `image2` VARCHAR(191) NULL,
    ADD COLUMN `image3` VARCHAR(191) NULL,
    ADD COLUMN `image4` VARCHAR(191) NULL,
    ADD COLUMN `image5` VARCHAR(191) NULL,
    ADD COLUMN `image6` VARCHAR(191) NULL,
    ADD COLUMN `image7` VARCHAR(191) NULL,
    ADD COLUMN `image8` VARCHAR(191) NULL,
    ADD COLUMN `image9` VARCHAR(191) NULL;
